### PR TITLE
Added titles to imgs so they display when user hovers

### PR DESCRIPTION
**Pull request by kronaemmanuel**
If a title prop is defined on an img tag, then it automatically displays the title on hover.

Changes made:
- Set title props having the same value as the alt prop

### CODE REVIEW

**Comment by sabique** [comment]
Hi @kronaemmanuel 

The enhancement needed the caption on hover as we do have on images in the gallery instead of the title attribute. The title attribute does show the title but its not a pretty way.

**Comment by kronaemmanuel** [comment]
Ok, i'm working on it.

**Comment by sabique** [comment]
Hi @kronaemmanuel 

Let me know if you're facing any issue. I will be happy to help :)

**Comment by kronaemmanuel** [comment]
I'm working on it. I'll let you know if there is any issue.

**Comment by kronaemmanuel** [comment]
I've made some changes. Lemme know if this is what you were looking for. :D

**Comment by sabique** [comment]
> Wow! It looks so dope 😀 You have done a great work. 🎉 

I have merged your changes and it's live on the site now. I will also add your name to the contributor's list. Cheers! 🎊

**Comment by sabique** [comment]
@all-contributors please add @kronaemmanuel  for design and code

**Pull request merged**
