### PR TITLE
Hotel overview mobile layout

### PR DESCRIPTION
**Pull request by thewhiteswan**
To create a legible hotel overview section for mobile view I used the flex-direction: column element, added some padding and slightly increased the font size for the hotel name, location and rating. 

Screen Shot 2019-10-05 at 9 56 29 PM

### CODE REVIEW

**Comment by sabique** [comment]
Hi @thewhiteswan 

I guess you have by mistake committed the package files as well. Kindly remove them.

And regarding the design, it looks better than before but it's occupying too much of space for a mobile screen. Can we add hotel name, stars and location in the same row?

Kindly let me know in case you need any help!

**Comment by thewhiteswan** [comment]
Thanks for the feedback @sabique :) 

I removed the package files. (Sorry! Still new at this.)

I also implemented the design changes you requested. I'm happy to tweak it again if you are not happy with it.

**Comment by sabique** [comment]
We learn by making mistakes @thewhiteswan, it happens with everyone.

And I have reviewed the updated design and it looks better but somehow the elements do not appear to be proper. For more clarity I have tweaked some changes and attaching the screenshot below:

**BEFORE**
PR-15-Before

**AFTER**
PR-15-After

I have just pushed the location at the right end and kept name and rating at the left. Also increased the font size of the rating. 

Let me know in case you need more clarity! I will be happy to help :)

**Review by sabique — CHANGES_REQUESTED** [review]
1. We can remove the **flex: 1 0 33%;** for the Name, Rating and City elements as they will automatically get the 33% space by applying the Justify-Content property in the parent element. But we don't have to do this because of point 2 given below.

2. We can set the **margin-right: auto** for the star element and it will push the location element to the end automatically. You can set the **margin-left: auto** to the location element and it will do the same. This is a very clean trick which I learnt recently.

3. We do not need to provide **display: flex** property to the rating average element.

4. We can remove the left/right padding for the stars, then it will get closer to the Name and makes more space between itself and location.

**Comment by thewhiteswan** [comment]
Thanks for the detailed response @sabique it was very helpful. I hope these changes fulfill what you asked for!

**Review by sabique — APPROVED** [review]

**Comment by sabique** [comment]
> Awesome job @thewhiteswan 🎉 🎉  You have done really amazing work! You should be proud of yourself. 😀


Your changes have been merged and it's live now. I will add your name to contributors list as soon as I will update the ReadMe file. Cheers! 🎊

**Comment by sabique** [comment]
@all-contributors please add @thewhiteswan for design and code

**Pull request merged**
