### PR TITLE
Added search functionality

### PR DESCRIPTION
**Pull request by louisefindlay23**
I've added a dropdown menu to the search bar while will display search results (#10) which are narrowed down when the user types by adding JavaScript and jQuery.

Nothing happens as of yet when a result is clicked but that functionality can be easily added when there are multiple hotel pages.

### CODE REVIEW

**Comment by sabique** [comment]
Hi @louisefindlay23, Thank you for all your effort. 

I have reviewed the changes and here is my feedback. 

**1. Header layout break for mobile screen** Kindly refers to the [original site on mobile](https://sabique.github.io/Booking-App-using-Flexbox/). 

PR-14-Small-Screen-Issue

2. Kindly keep the search bar at the centre and show the results below it. Also, we can remove the search results once the user comes out of search bar.

PR-14-Search-Result-Issue

Let me know in case you need an additional hand!

**Comment by sabique** [comment]
Hi @louisefindlay23 

The search results are coming over the search bar. We can solve it by reading the position of the search-bar element on the page using JavaScript and position the search results accordingly.

image

Also, once the search result appears then they don't hide back. We can hide them when the search-bar is not in focus.

Please let me know if you need any help! I will be happy to connect 💯

**Comment by louisefindlay23** [comment]
Hi @sabique. 

Yeah, that was an early commit when I thought it was working but it was only on a single screen size. Not sure how to get it to stay there when the screen size changes/

The search bar shows/hides reliably now when the input gains/loses focus. I tried a few different methods in jQuery until I found one that works every time.

**Comment by sabique** [comment]
Hi @louisefindlay23 

I checked the updated code and the search result closes now but somehow the design of the search bar broke for the desktop as well as for the mobile device.

You can refer to this exercise ([Follow Along Nav](https://sabique.github.io/JavaScript30/26%20-%20Stripe%20Follow%20Along%20Nav/)) which I have done some times ago where I change the size & position of the navigation items div according to its content size. Kindly look at its source, it will be really helpful and let me know in case you need any suggestions.

**Comment by sabique** [comment]
Hi @louisefindlay23 

Let me know if you're facing any issue. I will be happy to help :)

**Review by sabique — CHANGES_REQUESTED** [review]
Hi @louisefindlay23 

The functionality is working but the changes broke the design. 
image

Also, the search result list is not complementing the look and feel of the application.

Btw, I came across an HTML element named 'datalist' recently which provides the native autocomplete functionality for browsers. If you use this then you don't have to write a single line of jQuery nor do you need to update CSS and also it will avoid additional bytes of code.

More details:
[HTML DataList Tag - W3School](https://www.w3schools.com/tags/tag_datalist.asp)

Let me know in case you need any help.

**Pull request closed without merging**
